#!/bin/bash -x

# este script pode ser executado
# ou via curl:
#   sh -c "$(curl -fsSL https://raw.github.com/mestihudson/env/master/setup)"
# ou via wget:
#   sh -c "$(wget -qO- https://raw.github.com/mestihudson/env/master/setup)"
# ou via fetch:
#   sh -c "$(fetch -o - https://raw.github.com/mestihudson/env/master/setup)"

# atualização
sudo apt-get update
sudo apt-get upgrade

# curl
sudo apt install -y curl

# git
sudo apt-get install -y git xclip

# webcam ros
# https://florisvanbreugel.wordpress.com/2018/04/10/accessing-mac-webcam-in-ros-running-ubuntu-on-the-mac/
sudo apt install make guvcview -y
sudo mkdir -p /etc/local/src
cd /etc/local/src
sudo git clone https://github.com/patjak/bcwc_pcie.git
cd bcwc_pcie/firmware
sudo make
sudo make install
cd ..
sudo make
sudo install
sudo depmod
sudo modprobe -r bdc_pci
sudo modprobe facetimehd

# vim
sudo apt install vim -y

# tmux
sudo apt install tmux -y

# zsh
sudo apt-get install zsh -y
sudo chsh -s $(which zsh)
echo "exec zsh" >> ~/.bashrc

# fzf
git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
chmod +x ~/.fzf/install
~/.fzf/install

# oh-my-zsh
sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

# docker
cd /tmp
sh -c "$(curl -fsSL get.docker.com)"
sudo groupadd docker
sudo usermod -aG docker $USER
newgrp docker

# docker-compose
sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
docker-compose --version
