#!/bin/bash -x

# Este script pode ser executado
# ou via curl:
#   sh -c "$(curl -fsSL https://raw.github.com/mestihudson/env/master/setup)"
# ou via wget:
#   sh -c "$(wget -qO- https://raw.github.com/mestihudson/env/master/setup)"
# ou via fetch:
#   sh -c "$(fetch -o - https://raw.github.com/mestihudson/env/master/setup)"

# Atualização do sistema
sudo apt-get update
sudo apt-get upgrade

# Git - a version control system
sudo apt-get install -y git xclip

# Instalação Webcam ROS
# https://florisvanbreugel.wordpress.com/2018/04/10/accessing-mac-webcam-in-ros-running-ubuntu-on-the-mac/
sudo apt install make -y
sudo mkdir -p /etc/local/src
cd /etc/local/src
sudo git clone https://github.com/patjak/bcwc_pcie.git
cd bcwc_pcie/firmware
sudo make
sudo make install
cd ..
sudo make
sudo install
sudo depmod
sudo modprobe -r bdc_pci
sudo modprobe facetimehd
sudo apt install guvcview -y
guvcview
